# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json

---
version: 2
updates:
  - package-ecosystem: pip
    directory: /fails
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: /works
    schedule:
      interval: daily
